/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomNavigationMobile: typeof import('./src/components/ui/BottomNavigationMobile.vue')['default']
    CopyReferralLink: typeof import('./src/components/referral/CopyReferralLink.vue')['default']
    GlobalDrawer: typeof import('./src/components/ui/GlobalDrawer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Icon: typeof import('./src/components/common/Icon.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    PointsBalanceCard: typeof import('./src/components/referral/PointsBalanceCard.vue')['default']
    ReferralForm: typeof import('./src/components/referral/ReferralForm.vue')['default']
    ReferralHistoryTable: typeof import('./src/components/referral/ReferralHistoryTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/ui/Sidebar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
